### ISSUE TITLE
ImportError: No module named lz4.block

### ISSUE THREAD

**Issue by pandalatte** [python-lz4/python-lz4#182]
Hi everyone!
I'm trying to edit a search engine extension in Firefox Quantum. Some guy has posted a piece of code elsewhere that reads as

"#!/usr/bin/env python

import lz4.block as lb

infile = 'search.json.mozlz4'
outfile = 'search.json.mozlz4_'

inf = open(infile, 'rb')
inf.read(8)
data = lb.decompress(inf.read())
outf = open(outfile, 'wb')
outf.write(data)"
========================

So I did
"pip install lz4", add the requirements, then I execute this code, but it says

Traceback (most recent call last):
  File "./se", line 3, in <module>
    import lz4.block as lb
ImportError: No module named lz4.block

================
Do I need any extra libraries? Thanks a lot

**Comment by jonathanunderwood** [comment]
It looks like you have a very old version of the lz4 package, somehow. What's the output of `pip freeze`?

**Comment by jonathanunderwood** [comment]
No response from reporter so clsing this. Please feel free to re-open with more information.

**Comment by rahulgit1988** [comment]
stack@nti-itpf-d-os-04:~/devstack$ gnocchi-upgrade --create-legacy-resource-types
Traceback (most recent call last):
  File "/usr/local/bin/gnocchi-upgrade", line 7, in <module>
    from gnocchi.cli import upgrade
  File "/opt/stack/gnocchi/gnocchi/cli.py", line 32, in <module>
    from gnocchi import service
  File "/opt/stack/gnocchi/gnocchi/service.py", line 28, in <module>
    from gnocchi import opts
  File "/opt/stack/gnocchi/gnocchi/opts.py", line 26, in <module>
    import gnocchi.storage.ceph
  File "/opt/stack/gnocchi/gnocchi/storage/ceph.py", line 20, in <module>
    from gnocchi.storage import _carbonara
  File "/opt/stack/gnocchi/gnocchi/storage/_carbonara.py", line 29, in <module>
    from gnocchi import carbonara
  File "/opt/stack/gnocchi/gnocchi/carbonara.py", line 31, in <module>
    import lz4.block
ImportError: No module named block

pipfreeze >>
lz4==0.8.2
