### ISSUE TITLE
lz4 fails to import on mac osx

### ISSUE THREAD

**Issue by braingram** [python-lz4/python-lz4#267]
```bash
>> python -c "import lz4"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/bgraham/.pyenv/versions/lz4_macosx/lib/python3.10/site-packages/lz4/__init__.py", line 14, in <module>
    from ._version import (  # noqa: F401
ImportError: dlopen(/Users/bgraham/.pyenv/versions/lz4_macosx/lib/python3.10/site-packages/lz4/_version.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (_LZ4_versionNumber)
>> pip freeze
lz4==4.3.1
>>  sw_vers
ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115
```

Darwin Kernel Version 21.6.0
arm64

4.3.0 fails same as 4.3.1.

Installing 4.2.0 works without issue.

This may be related to PR #264

**Comment by jonathanunderwood** [comment]
Are you on an arm or intel mac?

**Comment by braingram** [comment]
I'm on arm64. Let me know if there's any more information I can supply

**Comment by jonathanunderwood** [comment]
If you do a `brew install lz4` does it work?

**Comment by braingram** [comment]
It does not appear to
```bash
>> brew list | grep lz4
lz4
>> python -c "import lz4"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/bgraham/.pyenv/versions/lz4_macosx/lib/python3.10/site-packages/lz4/__init__.py", line 14, in <module>
    from ._version import (  # noqa: F401
ImportError: dlopen(/Users/bgraham/.pyenv/versions/lz4_macosx/lib/python3.10/site-packages/lz4/_version.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (_LZ4_versionNumber)
>> pip freeze
lz4==4.3.1
```

**Comment by jonathanunderwood** [comment]
Have pushed a build for 4.3.2 - please test that once it hits PyPi (will take an hour ish)

**Comment by jonathanunderwood** [comment]
4.3.2 is now published.

**Comment by braingram** [comment]
Tested with 4.3.2 and it's working (with and without lz4 installed through homebrew). Thanks for the quick response!

**Comment by jonathanunderwood** [comment]
Great - thanks for reporting and testing, much appreciated.
